In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
from statsmodels.tsa.arima_model import ARMA

In [2]:
from weather_api import *

Za pomoca skryptu shelowego pobieramy dane dla konkretnego miasta i dostarczamy je w formie DataFrame. DataFrame został od razu "odchudzony" z danych nie wnoszących żadnych informacji (kolumny zawierające głównie wartości null).

In [3]:
df = get_data("zakopane")
df

Kod stacji Nazwa stacji   Rok  Miesiąc  Dzień  \
0     349190625     ZAKOPANE  2020        1      1   
1     349190625     ZAKOPANE  2020        1      2   
2     349190625     ZAKOPANE  2020        1      3   
3     349190625     ZAKOPANE  2020        1      4   
4     349190625     ZAKOPANE  2020        1      5   
..          ...          ...   ...      ...    ...   
542   349190625     ZAKOPANE  2019       12     27   
543   349190625     ZAKOPANE  2019       12     28   
544   349190625     ZAKOPANE  2019       12     29   
545   349190625     ZAKOPANE  2019       12     30   
546   349190625     ZAKOPANE  2019       12     31   

     Średnie dobowe zachmurzenie ogólne [oktanty]  \
0                                             4.3   
1                                             4.4   
2                                             2.5   
3                                             7.6   
4                                             7.9   
..                                            ...   
542                                           7.9   
543                                           8.0   
544                                           7.1   
545                                           6.0   
546                                           6.5   

     Średnia dobowa prędkość wiatru [m/s]  Średnia dobowa temperatura [°C]  \
0                                     2.0                             -1.7   
1                                     1.3                             -1.5   
2                                     1.4                             -1.1   
3                                     3.6                              0.8   
4                                     2.8                             -4.1   
..                                    ...                              ...   
542                                   2.1                             -2.0   
543                                   2.6                             -4.6   
544                                   0.9                             -7.3   
545                                   1.3                             -2.3   
546                                   2.8                              2.8   

     Średnia dobowe ciśnienie pary wodnej [hPa]  \
0                                           4.0   
1                                           3.1   
2                                           3.8   
3                                           5.4   
4                                           3.8   
..                                          ...   
542                                         4.8   
543                                         4.0   
544                                         3.2   
545                                         4.8   
546                                         5.0   

     Średnia dobowa wilgotność względna [%]  \
0                                      73.1   
1                                      56.8   
2                                      68.8   
3                                      83.6   
4                                      83.6   
..                                      ...   
542                                    91.3   
543                                    90.6   
544                                    88.3   
545                                    87.5   
546                                    68.3   

     Średnia dobowe ciśnienie na poziomie stacji [hPa]  \
0                                                929.5   
1                                                928.8   
2                                                922.4   
3                                                917.5   
4                                                924.4   
..                                                 ...   
542                                              920.5   
543                                              928.0   
544                                              933.2   
545                     

Wykorzystując założenie, że każda wartość większa od 0 w kolunach 'Suma opadu dzień' i 'Suma opadu noc' oznacza, że będzie padać odpowiednio w dzień i w nocy, dodajemy dwie kolumny z wartościami 0 - nie pada oraz 1 - pada.

In [4]:
value = []
data = df['Suma opadu dzień  [mm]']
data = data.to_numpy()
for row in data:
    if row == 0:
        value.append(0)
    elif row > 0:
        value.append(1)
df['deszcz w dzień']= value

value1 = []
data1 = df['Suma opadu noc   [mm]']
data1 = data1.to_numpy()
for row1 in data1:
    if row1 == 0:
        value1.append(0)
    elif row1 > 0:
        value1.append(1)
df['deszcz w nocy']= value1

df

Kod stacji Nazwa stacji   Rok  Miesiąc  Dzień  \
0     349190625     ZAKOPANE  2020        1      1   
1     349190625     ZAKOPANE  2020        1      2   
2     349190625     ZAKOPANE  2020        1      3   
3     349190625     ZAKOPANE  2020        1      4   
4     349190625     ZAKOPANE  2020        1      5   
..          ...          ...   ...      ...    ...   
542   349190625     ZAKOPANE  2019       12     27   
543   349190625     ZAKOPANE  2019       12     28   
544   349190625     ZAKOPANE  2019       12     29   
545   349190625     ZAKOPANE  2019       12     30   
546   349190625     ZAKOPANE  2019       12     31   

     Średnie dobowe zachmurzenie ogólne [oktanty]  \
0                                             4.3   
1                                             4.4   
2                                             2.5   
3                                             7.6   
4                                             7.9   
..                                            ...   
542                                           7.9   
543                                           8.0   
544                                           7.1   
545                                           6.0   
546                                           6.5   

     Średnia dobowa prędkość wiatru [m/s]  Średnia dobowa temperatura [°C]  \
0                                     2.0                             -1.7   
1                                     1.3                             -1.5   
2                                     1.4                             -1.1   
3                                     3.6                              0.8   
4                                     2.8                             -4.1   
..                                    ...                              ...   
542                                   2.1                             -2.0   
543                                   2.6                             -4.6   
544                                   0.9                             -7.3   
545                                   1.3                             -2.3   
546                                   2.8                              2.8   

     Średnia dobowe ciśnienie pary wodnej [hPa]  \
0                                           4.0   
1                                           3.1   
2                                           3.8   
3                                           5.4   
4                                           3.8   
..                                          ...   
542                                         4.8   
543                                         4.0   
544                                         3.2   
545                                         4.8   
546                                         5.0   

     Średnia dobowa wilgotność względna [%]  \
0                                      73.1   
1                                      56.8   
2                                      68.8   
3                                      83.6   
4                                      83.6   
..                                      ...   
542                                    91.3   
543                                    90.6   
544                                    88.3   
545                                    87.5   
546                                    68.3   

     Średnia dobowe ciśnienie na poziomie stacji [hPa]  \
0                                                929.5   
1                                                928.8   
2                                                922.4   
3                                                917.5   
4                                                924.4   
..                                                 ...   
542                                              920.5   
543                                              928.0   
544                                              933.2   
545                     

Usuwamy kolumny 'Status pomiaru PPPM' oraz 'Średnie dobowe ciśnienie na poziomie morza'. Obie te kolumny zawierają wartości, które mają takie same wartości (nic nie wnoszą).

In [5]:
df = df.drop(df.columns[11],axis = 1)
df = df.drop(df.columns[11],axis = 1)

df

Kod stacji Nazwa stacji   Rok  Miesiąc  Dzień  \
0     349190625     ZAKOPANE  2020        1      1   
1     349190625     ZAKOPANE  2020        1      2   
2     349190625     ZAKOPANE  2020        1      3   
3     349190625     ZAKOPANE  2020        1      4   
4     349190625     ZAKOPANE  2020        1      5   
..          ...          ...   ...      ...    ...   
542   349190625     ZAKOPANE  2019       12     27   
543   349190625     ZAKOPANE  2019       12     28   
544   349190625     ZAKOPANE  2019       12     29   
545   349190625     ZAKOPANE  2019       12     30   
546   349190625     ZAKOPANE  2019       12     31   

     Średnie dobowe zachmurzenie ogólne [oktanty]  \
0                                             4.3   
1                                             4.4   
2                                             2.5   
3                                             7.6   
4                                             7.9   
..                                            ...   
542                                           7.9   
543                                           8.0   
544                                           7.1   
545                                           6.0   
546                                           6.5   

     Średnia dobowa prędkość wiatru [m/s]  Średnia dobowa temperatura [°C]  \
0                                     2.0                             -1.7   
1                                     1.3                             -1.5   
2                                     1.4                             -1.1   
3                                     3.6                              0.8   
4                                     2.8                             -4.1   
..                                    ...                              ...   
542                                   2.1                             -2.0   
543                                   2.6                             -4.6   
544                                   0.9                             -7.3   
545                                   1.3                             -2.3   
546                                   2.8                              2.8   

     Średnia dobowe ciśnienie pary wodnej [hPa]  \
0                                           4.0   
1                                           3.1   
2                                           3.8   
3                                           5.4   
4                                           3.8   
..                                          ...   
542                                         4.8   
543                                         4.0   
544                                         3.2   
545                                         4.8   
546                                         5.0   

     Średnia dobowa wilgotność względna [%]  \
0                                      73.1   
1                                      56.8   
2                                      68.8   
3                                      83.6   
4                                      83.6   
..                                      ...   
542                                    91.3   
543                                    90.6   
544                                    88.3   
545                                    87.5   
546                                    68.3   

     Średnia dobowe ciśnienie na poziomie stacji [hPa]  \
0                                                929.5   
1                                                928.8   
2                                                922.4   
3                                                917.5   
4                                                924.4   
..                                                 ...   
542                                              920.5   
543                                              928.0   
544                                              933.2   
545                     

Przeprowadzamy konwersję kolumn Rok, Miesiąc, Dzień do formatu daty.

In [6]:
date = pd.to_datetime((df['Rok']*10000+df['Miesiąc']*100+df['Dzień']).apply(str),format='%Y%m%d')
df.insert(loc=2, column='Data', value=date)
for i in range(0,3):
    df = df.drop(df.columns[3],axis = 1)
df

Kod stacji Nazwa stacji       Data  \
0     349190625     ZAKOPANE 2020-01-01   
1     349190625     ZAKOPANE 2020-01-02   
2     349190625     ZAKOPANE 2020-01-03   
3     349190625     ZAKOPANE 2020-01-04   
4     349190625     ZAKOPANE 2020-01-05   
..          ...          ...        ...   
542   349190625     ZAKOPANE 2019-12-27   
543   349190625     ZAKOPANE 2019-12-28   
544   349190625     ZAKOPANE 2019-12-29   
545   349190625     ZAKOPANE 2019-12-30   
546   349190625     ZAKOPANE 2019-12-31   

     Średnie dobowe zachmurzenie ogólne [oktanty]  \
0                                             4.3   
1                                             4.4   
2                                             2.5   
3                                             7.6   
4                                             7.9   
..                                            ...   
542                                           7.9   
543                                           8.0   
544                                           7.1   
545                                           6.0   
546                                           6.5   

     Średnia dobowa prędkość wiatru [m/s]  Średnia dobowa temperatura [°C]  \
0                                     2.0                             -1.7   
1                                     1.3                             -1.5   
2                                     1.4                             -1.1   
3                                     3.6                              0.8   
4                                     2.8                             -4.1   
..                                    ...                              ...   
542                                   2.1                             -2.0   
543                                   2.6                             -4.6   
544                                   0.9                             -7.3   
545                                   1.3                             -2.3   
546                                   2.8                              2.8   

     Średnia dobowe ciśnienie pary wodnej [hPa]  \
0                                           4.0   
1                                           3.1   
2                                           3.8   
3                                           5.4   
4                                           3.8   
..                                          ...   
542                                         4.8   
543                                         4.0   
544                                         3.2   
545                                         4.8   
546                                         5.0   

     Średnia dobowa wilgotność względna [%]  \
0                                      73.1   
1                                      56.8   
2                                      68.8   
3                                      83.6   
4                                      83.6   
..                                      ...   
542                                    91.3   
543                                    90.6   
544                                    88.3   
545                                    87.5   
546                                    68.3   

     Średnia dobowe ciśnienie na poziomie stacji [hPa]  \
0                                                929.5   
1                                                928.8   
2                                                922.4   
3                                                917.5   
4                                                924.4   
..                                                 ...   
542                                              920.5   
543                                              928.0   
544                                              933.2   
545                                              931.0   
546                                              924.5   

     Suma opadu dzień  [mm]  Suma opadu

In [7]:
df.sort_values(by=['Data'], inplace=True)
df

Kod stacji Nazwa stacji       Data  \
182   349190625     ZAKOPANE 2019-01-01   
183   349190625     ZAKOPANE 2019-01-02   
184   349190625     ZAKOPANE 2019-01-03   
185   349190625     ZAKOPANE 2019-01-04   
186   349190625     ZAKOPANE 2019-01-05   
..          ...          ...        ...   
177   349190625     ZAKOPANE 2020-06-26   
178   349190625     ZAKOPANE 2020-06-27   
179   349190625     ZAKOPANE 2020-06-28   
180   349190625     ZAKOPANE 2020-06-29   
181   349190625     ZAKOPANE 2020-06-30   

     Średnie dobowe zachmurzenie ogólne [oktanty]  \
182                                           6.6   
183                                           7.8   
184                                           8.0   
185                                           7.9   
186                                           7.9   
..                                            ...   
177                                           6.4   
178                                           5.9   
179                                           3.6   
180                                           4.9   
181                                           2.8   

     Średnia dobowa prędkość wiatru [m/s]  Średnia dobowa temperatura [°C]  \
182                                   2.8                             -1.0   
183                                   3.3                             -3.7   
184                                   1.6                             -7.5   
185                                   1.5                             -8.0   
186                                   1.6                             -3.4   
..                                    ...                              ...   
177                                   1.1                             17.7   
178                                   2.3                             21.2   
179                                   1.5                             19.6   
180                                   1.5                             17.7   
181                                   1.9                             17.0   

     Średnia dobowe ciśnienie pary wodnej [hPa]  \
182                                         5.0   
183                                         4.2   
184                                         3.0   
185                                         2.7   
186                                         4.3   
..                                          ...   
177                                        14.4   
178                                        14.1   
179                                        15.8   
180                                        14.8   
181                                        11.5   

     Średnia dobowa wilgotność względna [%]  \
182                                    84.9   
183                                    89.8   
184                                    85.5   
185                                    81.3   
186                                    90.5   
..                                      ...   
177                                    74.0   
178                                    56.9   
179                                    71.9   
180                                    76.5   
181                                    62.0   

     Średnia dobowe ciśnienie na poziomie stacji [hPa]  \
182                                              918.4   
183                                              911.3   
184                                              919.1   
185                                              922.1   
186                                              912.7   
..                                                 ...   
177                                              921.9   
178                                              918.7   
179                                              919.0   
180                                              915.3   
181                                              915.9   

     Suma opadu dzień  [mm]  Suma opadu

Za pomocą szeregów czasowych przewidujemy wartości każdego z parametrów na następne 7 dni. Następnie scalamy to w DataFrame.

In [8]:
#przewidywanie przyszłych parametrów
def make_predict(nazwa_kolumny,ilosc_dni):
    df2 = df[['Data',nazwa_kolumny]]
    df2.index = pd.DatetimeIndex(df2['Data'])
    model = ARMA(df2[nazwa_kolumny], order=(4, 2))
    model_fit = model.fit(disp=False)
    forecast = model_fit.predict(len(df2),len(df2)+ilosc_dni)
    return forecast[:][:]
#stworzenie zbioru danych z przewidywanymi parametrami

predicted_data = [] 
predicted_data.append(make_predict('Średnie dobowe zachmurzenie ogólne [oktanty]',7))
predicted_data.append(make_predict('Średnia dobowa prędkość wiatru [m/s]',7))
predicted_data.append(make_predict('Średnia dobowa temperatura [°C]',7))
predicted_data.append(make_predict('Średnia dobowe ciśnienie pary wodnej [hPa]',7))
predicted_data.append(make_predict('Średnia dobowa wilgotność względna [%]',7))
predicted_data.append(make_predict('Średnia dobowe ciśnienie na poziomie stacji [hPa]',7))

/home/albert/.local/lib/python3.6/site-packages/statsmodels/tsa/base/tsa_model.py:527: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  % freq, ValueWarning)
/home/albert/.local/lib/python3.6/site-packages/statsmodels/tsa/base/tsa_model.py:527: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  % freq, ValueWarning)
/home/albert/.local/lib/python3.6/site-packages/statsmodels/tsa/base/tsa_model.py:527: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  % freq, ValueWarning)
/home/albert/.local/lib/python3.6/site-packages/statsmodels/tsa/base/tsa_model.py:527: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  % freq, ValueWarning)
/home/albert/.local/lib/python3.6/site-packages/statsmodels/tsa/base/tsa_model.py:527: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  % freq, Valu

In [9]:
df1 = pd.DataFrame(predicted_data, index=['Średnie dobowe zachmurzenie ogólne [oktanty]','Średnia dobowa prędkość wiatru [m/s]','Średnia dobowa temperatura [°C]','Średnia dobowe ciśnienie pary wodnej [hPa]','Średnia dobowa wilgotność względna [%]','Średnia dobowe ciśnienie na poziomie stacji [hPa]'])
df1 = df1.T
df1

Średnie dobowe zachmurzenie ogólne [oktanty]  \
2020-07-01                                      4.296043   
2020-07-02                                      5.094571   
2020-07-03                                      5.197881   
2020-07-04                                      5.407627   
2020-07-05                                      5.347958   
2020-07-06                                      5.439300   
2020-07-07                                      5.378912   
2020-07-08                                      5.432831   

            Średnia dobowa prędkość wiatru [m/s]  \
2020-07-01                              1.733466   
2020-07-02                              1.624096   
2020-07-03                              1.607147   
2020-07-04                              1.594438   
2020-07-05                              1.606690   
2020-07-06                              1.600912   
2020-07-07                              1.612861   
2020-07-08                              1.607452   

            Średnia dobowa temperatura [°C]  \
2020-07-01                        16.381971   
2020-07-02                        16.098008   
2020-07-03                        15.965382   
2020-07-04                        15.908032   
2020-07-05                        15.862905   
2020-07-06                        15.817733   
2020-07-07                        15.768035   
2020-07-08                        15.716218   

            Średnia dobowe ciśnienie pary wodnej [hPa]  \
2020-07-01                                   11.765728   
2020-07-02                                   12.436361   
2020-07-03                                   12.838714   
2020-07-04                                   12.796538   
2020-07-05                                   12.728555   
2020-07-06                                   12.596476   
2020-07-07                                   12.552744   
2020-07-08                                   12.474294   

            Średnia dobowa wilgotność względna [%]  \
2020-07-01                               68.369018   
2020-07-02                               71.960170   
2020-07-03                               74.172265   
2020-07-04                               74.859559   
2020-07-05                               75.579014   
2020-07-06                               75.530651   
2020-07-07                               75.883523   
2020-07-08                               75.658874   

            Średnia dobowe ciśnienie na poziomie stacji [hPa]  
2020-07-01                                         917.199449  
2020-07-02                                         917.384980  
2020-07-03                                         916.979461  
2020-07-04                                         917.309048  
2020-07-05                                         917.441080  
2020-07-06                                         917.219927  
2020-07-07                                         917.309627  
2020-07-08                                         917.407322

Normalizujemy DataFrame'y metodą min-max.

In [10]:
columns_to_normalize = [[5],[6],[8],[9],[10]]
normalize_particular_columns(df, columns_to_normalize)
columns_to_normalize = [[5],[0],[1],[2],[3],[4]]
normalize_particular_columns(df1, columns_to_normalize)

Dzielimy dane na zbiory treningowe i testowe.

In [11]:
X = df[[df.columns[3],df.columns[4],df.columns[5],df.columns[6],df.columns[7],df.columns[8]]]
y = df[[df.columns[11]]]

In [12]:
Xtrain, Xtest, ytrain, ytest  = train_test_split(X,y,test_size=0.2,random_state=75)

## Model SVN 

In [13]:
clf= svm.SVC(kernel='linear', C=1.0)
clf.fit(Xtrain,ytrain)

SVC(kernel='linear')

In [36]:
ypred = clf.predict(Xtest)
clf_score = clf.score(Xtest,ytest)
print(f"Dokładoność modelu SVN wynosi {clf_score:.2f}")

Dokładoność modelu SVN wynosi 0.79


In [16]:
confusion_matrix(ytest,ypred)

array([[54,  5],
       [18, 33]])

## Model logistic regresion

In [37]:
logistic_regression= LogisticRegression()
logistic_regression.fit(Xtrain,ytrain)
y_pred_r=logistic_regression.predict(Xtest)
log_accur = accuracy_score(ytest, y_pred_r)
print(f"Dokładoność modelu regresji logistycznej wynosi {log_accur:.2f}")

Dokładoność modelu regresji logistycznej wynosi 0.80


In [33]:
confusion_matrix(ytest,y_pred_r)

array([[55,  4],
       [18, 33]])

## Model KNN

In [38]:
knn = KNeighborsClassifier()
knn.fit(Xtrain, ytrain)
y_pred_knn = knn.predict(Xtest)
accurKNN = accuracy_score(ytest, y_pred_knn)

print(f"Dokładoność modelu kNN wynosi {accurKNN:.2f}")

Dokładoność modelu kNN wynosi 0.73


In [35]:
confusion_matrix(ytest,y_pred_knn)

array([[47, 12],
       [18, 33]])

### Test danych przewidzianych

In [25]:
result_knn = knn.predict(df1)
result_log = logistic_regression.predict(df1)
result_svn = clf.predict(df1)

In [26]:
result_knn

array([0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
result_log

array([0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
result_svn

array([0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
target_names = ['brak deszczu', 'deszcz']
report = classification_report(ytest, y_pred_knn, target_names= target_names)
print(report)

precision    recall  f1-score   support

brak deszczu       0.72      0.80      0.76        59
      deszcz       0.73      0.65      0.69        51

    accuracy                           0.73       110
   macro avg       0.73      0.72      0.72       110
weighted avg       0.73      0.73      0.73       110

